Repository MninaTB/AE_Quiz_Projekt24, pull requests merged in 2021-06, with the labels that each got.

#76 feat(src): Start GUI nach MVC Pattern
  src/Main.java
  src/controller/Start.java
  src/ui/Router.java
  src/view/Start.java
Labels: task

#77 feat(src): Game GUI nach MVC Pattern
  src/Main.java
  src/controller/Categories.java
  src/controller/Game.java
  src/controller/Screen.java
  src/controller/Start.java
  src/ui/Registry.java
  src/view/Game.java
Labels: task

#78 feat(src): Result GUI nach MVC Pattern
  src/controller/Game.java
  src/controller/Result.java
  src/ui/Registry.java
  src/view/Result.java
Labels: task

#80 Fix/question parser #79
  Makefile
  src/questions/QuestionParser.java
Labels: bug

#81 feat(src): Options GUI nach MVC Pattern
  src/controller/Options.java
  src/view/Options.java
  src/view/OptionsQuestionRow.java
Labels: task

#83 feat(src): Edit GUI nach MVC Pattern
  src/controller/Create.java
  src/controller/Edit.java
  src/controller/Options.java
  src/controller/Screen.java
  src/ui/Registry.java
  src/view/Edit.java
Labels: task

#88 feat(src): Kategorie GUI nach MVC Pattern
  src/controller/Category.java
  src/controller/Screen.java
  src/controller/Start.java
  src/ui/Registry.java
  src/view/Category.java
Labels: task

#87 feat(questions): stelle Kategorien wieder her
  questions.json
Labels: bug

#103 fix(src/controller): uebergebe spielstand an result screen
  src/controller/Category.java
  src/controller/Game.java
  src/controller/Result.java
  src/game/State.java
Labels: bug

#104 feat(src/Main): unterstutze Datenbank verbindung ueber args
  src/Main.java
Labels: enhancement
