Repository MninaTB/AE_Quiz_Projekt24, pull requests merged in 2021-05, with the labels that each got.

#49 Feat/sql skrpt#26
  scripts/SQLBefehle.sql
Labels: task

#48 feat(Makefile): nutze junit5 standalone jar
  .github/workflows/main.yml
  Makefile
Labels: enhancement, work in progress

#57 Kommentare hinzugefuegt an die jeweiligen Methoden und Klassen
  src/Main.java
  src/game/MissingQuestionsException.java
  src/game/MockQuestionStoreTest.java
  src/game/State.java
  src/game/StateBuilder.java
  src/game/StateBuilderTest.java
  src/game/StateTest.java
  src/questions/Category.java
  src/questions/Question.java
  src/questions/QuestionParser.java
  src/questions/QuestionParserTest.java
  src/questions/QuestionStore.java
Labels: task

#68 Feat/UI architektur #62
  src/Main.java
  src/controller/Controller.java
  src/controller/Screen.java
  src/controller/Start.java
  src/controller/Switcher.java
  src/game/MockQuestionStoreTest.java
  src/game/State.java
  src/game/StateBuilder.java
  src/game/StateBuilderTest.java
  src/game/StateTest.java
  src/model/Category.java
  src/model/Question.java
  src/questions/QuestionParser.java
  src/questions/QuestionParserTest.java
  src/questions/QuestionStore.java
  src/ui/Registry.java
  src/ui/Router.java
  src/view/Start.java
Labels: enhancement, work in progress

#53 feat(doc): Dokumentation fuer GUI Ideen ueberarbeitet
  doc/GUI_IDEAS.md
  doc/assets/EditGUI.png
  doc/assets/EditableEditGUI.drawio
  doc/assets/EditableEndGUI.drawio
  doc/assets/EditableGameGUI.drawio
  doc/assets/EditableOptionsGUI.drawio
  doc/assets/EditableResultGUI.drawio
  doc/assets/EditableStartGUI.drawio
  doc/assets/EndGUI.png
  doc/assets/GameGUI.png
  doc/assets/OptionsGUI.png
  doc/assets/ResultGUI.png
  doc/assets/StartGUI.png
Labels: documentation

#67 Habe das Mindestlevel hinzugefuegt und die Tests jeweils angepasst
  src/game/StateBuilder.java
  src/game/StateBuilderTest.java
Labels: task

#75 fix(src/ui): entferne nicht alle components von Frame
  src/Main.java
  src/controller/Categories.java
  src/controller/Options.java
  src/controller/Start.java
  src/ui/Registry.java
  src/ui/Router.java
Labels: needs/testing
